MENSAJERIA_OLTP:
  drivername: postgresql
  dbname: ProyectoCienciaDeDatos
  user: daniel
  password: 1234
  host: localhost
  port: 5432

ETL_PROCESS:
  drivername: postgresql
  dbname: BodegaProyecto
  user: daniel
  password: 1234
  host: localhost
  port: 5432

LOAD_DIMENSIONS:
  True